### ISSUE TITLE
what is apache server-info module?

### ISSUE THREAD

**Issue by BarbzYHOOL** [zioalex/unused_apache_modules#2]
a2enmod server-info
ERROR: Module server-info does not exist!

**Comment by BarbzYHOOL** [comment]
ok it's "info" not "server-info"

**Comment by BarbzYHOOL** [comment]
no in fact it's not because the fetched file is very different than your example and then the script doesn't work :(

**Comment by zioalex** [comment]
The script can be adapted. Nevertheless I am not sure about the difference between the info and the server-info module.
